[build]
  publish = "frontend"

[[edge_functions]]
  path = "/*"
  function = "auth"

[[headers]]
  for = "/sw.js"
  [headers.values]
    Cache-Control = "no-cache"

[[headers]]
  for = "/manifest.json"
  [headers.values]
    Content-Type = "application/manifest+json"
